version: "3.6"

services:
  woocommerce-dev:
    container_name: woocommerce-dev
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:-5.5.3}
        WOOCOMMERCE_VERSION: ${WOOCOMMERCE_VERSION:-4.8.0}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${WORDPRESS_DEV_PORT:-8090}:80"
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/wordpress/wp-content/plugins/${PROJECT_NAME:-clearpay-gateway-europe-for-woocommerce}
    extra_hosts:
      - "woocommerce-dev.docker:127.0.0.1"
#    networks:
#      - wordpress_default_network
    labels:
      - com.clearpay.plugin-development-docker.wcinstance

  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}


  woocommerce-test:
    container_name: woocommerce-test
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db-test
    volumes:
      - ./:/pagantis
    environment:
      - WORDPRESS_DB_HOST=db-test
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_URL=woocommerce-test.docker:8091
      - WORDPRESS_SITE_NAME=PgWooCommerce
      - WORDPRESS_ADMIN_EMAIL=demo@woocommerceshop.com
      - WORDPRESS_ADMIN_USER=admin
      - WORDPRESS_ADMIN_PASSWORD=woocommerceshop_demo
    ports:
      - "8091:80"
    working_dir: /pagantis
    extra_hosts:
      - "woocommerce-test.docker:127.0.0.1"
    networks:
      - wordpress_default_network
    labels:
      - com.clearpay.plugin-development-docker.wcinstance

  db-test:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress

  selenium:
    image: selenium/standalone-chrome:${SELENIUM_VERSION:-3.141.59}
    ports:
      - "4444:4444"
    extra_hosts:
      - "woocommerce-test.docker:${DOCKERHOST}"
      - "woocommerce-dev.docker:${DOCKERHOST}"
#    networks:
#     - wordpress_default_network

networks:
  wordpress_default_network: